//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feb13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int ID_major { get; set; }
        public Nullable<int> ID_faculty { get; set; }
        public string majorName { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
